server:
  port: 8866

spring:
    application:
        name: mq-service
    rabbitmq:
      host: localhost
      username: guest
      password: guest
      port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



