server:
  port: 5000
spring:
  application:
    name: admin-server
  mail:
    username: 18086417780@163.com
    password: llc123456
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
    host: smtp.163.com
  boot:
    admin:
      notify:
        mail:
          to: 18086417780@163.com
          from: 18086417780@163.com


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

