server:
  port: 8099
spring:
  application:
    name: SpringBootAdmin
  security:
    user:
      name: anxminise
      password: 123456
  boot:
    admin:
      ui:
        title: 忧臣解读

  client:
    serviceUrl:
      defaultZone: http:localhost:8761/eureka