eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-HI
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  eureka:
      enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000