eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: service-zuul
  main:
    allow-bean-definition-overriding: true
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-CONSUME
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  eureka:
      enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000